DLP-1 Registration
Balazs14-hun/Delphi pull request #1
Opened 2024-03-29 12:59 UTC by Balazs14-hun

2024-03-29 13:29 UTC, szabolcs3 requested changes

2024-03-29 13:29 UTC, szabolcs3 commented on app/Http/Controllers/UserController.php
> +    $attributes = $request->validate([
Please use the validations [like this](https://laravel.com/docs/11.x/validation#creating-form-requests) 😄 . You don't need to define the rules here.

2024-03-29 13:29 UTC, szabolcs3 commented on app/Http/Controllers/UserController.php
> +    return redirect('/');
Please use [named routes](https://laravel.com/docs/11.x/routing#named-routes)

2024-03-29 13:29 UTC, szabolcs3 commented on resources/js/Components/BaseFormInput.vue
> +      <ExclamationCircleIcon
Yes, you can do this or if you want to make it more beautiful. You can:
```
<slot name="icon" />
```

And you can overwrite it with
```
<template #icon>
</template>
```

[Read more](https://vuejs.org/guide/components/slots.html)

2024-03-29 13:29 UTC, szabolcs3 commented on resources/js/Components/BaseSidePanel.vue
> +          <p class="">help@delphi.com</p>
Empty class 😛

2024-03-29 13:29 UTC, szabolcs3 commented on resources/js/Components/RegisterSidePanel.vue
> +      body="Intoduceți adresa de email și alegeți parola"
Missing `r` 😛

2024-03-29 13:29 UTC, szabolcs3 commented on resources/js/Components/RegisterSidePanelItem.vue
> +    :class="[isFirst ? 'pb-4' : '', isLast ? 'pt-4' : '', !isLast && !isFirst ? 'pb-4 pt-4' : '']"
Check this [one](https://vuejs.org/guide/essentials/class-and-style#binding-html-classes) 😄

2024-03-29 13:29 UTC, szabolcs3 commented on resources/js/Components/RegisterSidePanelItem.vue
> +    <CheckCircleIcon
I'm pondering whether this combination of v-if and v-else can doable using a mapper.

2024-03-29 13:29 UTC, szabolcs3 commented on tailwind.config.js
> +        primary: {
Nice 👏

2024-03-29 13:29 UTC, szabolcs3 commented on tailwind.config.js
> +        sans: ['Inter var', ...defaultTheme.fontFamily.sans]
Just simply `Inter` no?

2024-03-29 13:29 UTC, szabolcs3 commented on resources/js/Pages/Users/Create.vue
> +      rel="stylesheet"
I don't think this should be here 🤔

2024-03-29 13:29 UTC, szabolcs3 commented on resources/js/Components/BaseContainer.vue
Is this a layout for the website or just a container?

2024-04-01 06:13 UTC, Balazs14-hun commented on resources/js/Components/BaseContainer.vue
It's just a container for registration like cards. Login has the same container, so i thought i should extract it.

2024-04-01 08:07 UTC, szabolcs3 approved these changes

2024-04-01 08:16 UTC, merged