DLP-2 Invite team member by email
Balazs14-hun/Delphi pull request #2
Opened 2024-04-09 09:02 UTC by Balazs14-hun

2024-04-09 10:48 UTC, szabolcs3 requested changes

2024-04-09 10:48 UTC, szabolcs3 commented on app/Events/Invited.php
> +    $pepper = 'TxMySPU6UIcTCdT';
Take a look at to [this](https://laravel.com/docs/11.x/strings#method-str-uuid)

2024-04-09 10:48 UTC, szabolcs3 commented on app/Events/Invited.php
> +    $team = Team::where('id', $currentUser['team_id'])->first();
Please use the `find()` method here

2024-04-09 10:48 UTC, szabolcs3 commented on app/Events/Invited.php
> +    $inviteToken = Hash::make($user->created_at->toDateTimeString() . $pepper);
Please use template literals instead of concatenation.

2024-04-09 10:48 UTC, szabolcs3 commented on app/Events/Invited.php
> +      'http://localhost:8000/users/create?id=' . $id . '&token=' . $inviteToken . '&role=' . $role;
I don't think that the `BASE_URL` will be always `localhost:8000` 😉. Get these values from .env and url encode the query params.

2024-04-09 10:48 UTC, szabolcs3 commented on app/Http/Controllers/InviteController.php
> +    foreach ($request['emails'] as $index => $recipient) {
Please use eloquent methods!

2024-04-09 10:48 UTC, szabolcs3 commented on app/Http/Controllers/InviteController.php
> +    if ($token) {
if in if? 🤔

2024-04-09 10:48 UTC, szabolcs3 commented on app/Http/Controllers/InviteController.php
> +    $user->name = $request['name'];
Please use `$request->input()` method

2024-04-09 10:48 UTC, szabolcs3 commented on app/Http/Controllers/UserController.php
> +    if ($user['is_admin']) {
Can't we do this more simple?

2024-04-09 10:48 UTC, szabolcs3 commented on app/Mail/InviteTeamMember.php
> +  // prettier-ignore
Prettier-ignore? 🤔

2024-04-09 10:48 UTC, szabolcs3 commented on app/Models/User.php
> +  protected $fillable = ['name', 'email', 'password', 'is_admin', 'role_id', 'team_id'];
Instead of `$fillable` I think it's better to use `$guarded` the array will contain less element.

2024-04-09 10:48 UTC, szabolcs3 commented on database/factories/UserFactory.php
> +      'role_id' => fake()->numberBetween(1, 4),
Can't we take this `id` from the database?

2024-04-09 10:48 UTC, szabolcs3 commented on database/migrations/0001_01_01_000000_create_users_table.php
Don't you need to remove the foreign relation on `down()`? 🤔

2024-04-09 10:48 UTC, szabolcs3 commented on resources/views/vendor/mail/html/themes/default.css
> +  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif,
Please add Inter into the font-family to be consistent 😄

2024-04-09 10:48 UTC, szabolcs3 commented on routes/web.php
> +  Route::get('/', function () {
Please move this to a controller

2024-04-09 10:48 UTC, szabolcs3 commented on routes/web.php
> +  Route::get('/invites/create', [InviteController::class, 'create'])->name('invite_team');
Take a look at [this](https://laravel.com/docs/11.x/routing#route-group-name-prefixes) 😄

2024-04-09 10:48 UTC, szabolcs3 commented on routes/web.php
> +  Route::get('/schedule/create', function () {
I think you forgot this route here 😂

2024-04-09 11:07 UTC, zsolt-wbg requested changes

2024-04-09 11:07 UTC, zsolt-wbg commented on resources/js/Components/RegisterSidePanel.vue
> +  if (step === props.registrationState) {
Please use a functions map like in the InviteForm.vue component at placeholderMapper, just pass the step variable as parameter. (If you need help, just tell me :) )

2024-04-09 11:07 UTC, zsolt-wbg commented on resources/js/Pages/Users/Create.vue
> +})
You can optimize it like this:
`const isInvited = computed(() => params.size === 3 && params.has('id') && params.has('token') && params.has('role') })`

Try to avoid unnecessary conditions :)

2024-04-09 11:07 UTC, zsolt-wbg commented on resources/js/Pages/Welcome.vue
> +const page = usePage<any>()
Please look after if you get a type for usePage, otherwise you can remove the any type. In typescript try to avoid **any** type as much as possible.

2024-04-09 12:09 UTC, szabolcs3 commented on app/Http/Controllers/InviteController.php
> +    foreach ($request['emails'] as $index => $recipient) {
Collection methods sorry my bad 🙏  [like this one](https://laravel.com/docs/11.x/collections#method-each)

2024-04-10 06:36 UTC, Balazs14-hun commented on app/Mail/InviteTeamMember.php
> +  // prettier-ignore
fixed

2024-04-10 10:17 UTC, Balazs14-hun commented on database/migrations/0001_01_01_000000_create_users_table.php
I forgot about the foreignId constraint, that's why it worked.
Now i added the constraint and on down() removed it.

2024-04-10 10:48 UTC, Balazs14-hun commented on routes/web.php
> +  Route::get('/schedule/create', function () {
It's a placeholder for the next feature and a route for the button press on the invitation form that skips that step.

2024-04-11 07:35 UTC, szabolcs3 requested changes

2024-04-11 07:35 UTC, szabolcs3 commented on app/Events/Invited.php
> +    $inviteToken = Hash::make("{$user->created_at->toDateTimeString()}{$uuid}");
<img src="https://media1.giphy.com/media/1d5KyiBWoux4fEXpE6/giphy.gif"/>

2024-04-11 07:35 UTC, szabolcs3 commented on app/Events/Invited.php
> +    //dd($url);
You can remove this comment 😛

2024-04-11 07:35 UTC, szabolcs3 commented on app/Events/Invited.php
> +      'users/create?id=' .
We can import this from .env `users/create`

2024-04-11 07:35 UTC, szabolcs3 commented on app/Events/Invited.php
> +      urlencode($id) .
What if you concatenate it first and after that encode it? 🤔

2024-04-11 07:35 UTC, szabolcs3 commented on app/Http/Controllers/InviteController.php
> +    $collection = collect($request->input('emails'));
Instead of `collection` can you give a more meaningful and self-explanatory variable name like `$emails`?

2024-04-11 07:35 UTC, szabolcs3 commented on app/Http/Controllers/UserController.php
> +    unset($user['is_admin']);
Can I ask why you unset the `is_admin` property?

2024-04-11 07:35 UTC, szabolcs3 commented on database/factories/UserFactory.php
> +      'role_id' => fake()->numberBetween(1, $numOfRoles),
Hmm. We should use something like `Roles::find($random)->id`

2024-04-11 07:35 UTC, szabolcs3 commented on resources/js/Components/InviteForm.vue
> +          @click="router.visit(route('schedule'))"
Can you create a separate function for this one?

2024-04-11 07:35 UTC, szabolcs3 commented on resources/js/Components/InviteForm.vue
> +        let key = 'emails.' + index
Please modify it with backticks

2024-04-11 07:35 UTC, szabolcs3 commented on resources/js/Components/RegisterForm.vue
>  function changePasswordType() {
Can you solve it with ternary operation?

2024-04-11 07:35 UTC, szabolcs3 commented on resources/js/Components/RegisterSidePanel.vue
> +const stateMapper = (step: number): ItemState => {
Can you use function please instead of arrow function?

2024-04-11 10:02 UTC, szabolcs3 approved these changes

2024-04-11 10:18 UTC, zsolt-wbg approved these changes

2024-04-11 10:55 UTC, merged