DLP-3, Set open hours after registration
Balazs14-hun/Delphi pull request #3
Opened 2024-04-17 12:05 UTC by Balazs14-hun

2024-04-17 12:50 UTC, szabolcs3 requested changes

2024-04-17 12:50 UTC, szabolcs3 commented on app/Http/Controllers/OpeningHoursController.php
> +    foreach ($request->validated()['formDays'] as $key => $value) {
Instead of foreach, please use [collections](https://laravel.com/docs/11.x/collections#method-each).

2024-04-17 12:50 UTC, szabolcs3 commented on app/Http/Controllers/UserController.php
> +    if ($team) {
You can put this if's content into this `if ($request->is_admin)` 🤔 . Because if the user is admin, it should have a team.

2024-04-17 12:50 UTC, szabolcs3 commented on app/Http/Requests/StoreOpeningHoursRequest.php
> +      'formDays.*.openHour' => ['required', 'max:255'],
We should make stricter rules for the `openHour` and for the `closeHour`

2024-04-18 07:59 UTC, zsolt-wbg requested changes

2024-04-18 07:59 UTC, zsolt-wbg commented on resources/js/Components/OpeningHoursForm.vue
> +interface Day {
Can you move Day, FormDays and Form interfaces into a separate ts file named **form-day** for ex. please? It's a better approach to declare types/interfaces in the model/types folder

2024-04-18 07:59 UTC, zsolt-wbg commented on resources/js/Components/OpeningHoursForm.vue
> +const hoursStr: string[] = [
Can you create a function to generate these hours please? It's a little bit ugly, and it isn't the best approach. Let's create a utlis folder (if don't have) and add a **helper.ts** file where you can create general functions. 

Here are some solutions which can help to you:

- https://codereview.stackexchange.com/questions/128260/populating-an-array-with-times-with-half-hour-interval-between-them

- https://gist.github.com/indexzero/6261ad9292c78cf3c5aa69265e2422bf

2024-04-18 07:59 UTC, zsolt-wbg commented on resources/js/Components/OpeningHoursForm.vue
> +  return days.value.some((day) => day.isChecked)
Use shorter version pls (without return)

2024-04-18 07:59 UTC, zsolt-wbg commented on resources/js/Components/OpeningHoursForm.vue
> +  const mappedHours: string[] = filteredHours.map((hour) => hourMapper.getValue(hour) ?? 'hh:mm')
You can directly return mappedHours

2024-04-18 07:59 UTC, zsolt-wbg commented on resources/js/twoWayMap.ts
> +export default class twoWayMap<Key, Value> {
Why do u need this class? :)

2024-04-18 10:43 UTC, Balazs14-hun commented on resources/js/twoWayMap.ts
> +export default class twoWayMap<Key, Value> {
Moved to utils/helper.ts and explained usage with comment.

2024-04-18 11:17 UTC, zsolt-wbg approved these changes

2024-04-18 12:06 UTC, szabolcs3 requested changes

2024-04-18 13:24 UTC, szabolcs3 approved these changes

2024-04-18 13:27 UTC, merged